--USE master
--DROP DATABASE CINEPLUS

CREATE DATABASE CINEPLUS
ON PRIMARY(
NAME=CINEPLUSDATA, FILENAME='C:\BD\CINEPLUS\CINEPLUZDATA.mdf',
SIZE=50MB,
MAXSIZE=600MB,
FILEGROWTH=10%
)
LOG ON(
NAME=CINEPLUSLOG, FILENAME='C:\BD\CINEPLUS\CINEPLUZLOG.ldf',
SIZE=30MB,
MAXSIZE=300MB,
FILEGROWTH=10%
)

USE CINEPLUS

--DROP TABLE TIPO_FUNCION
CREATE TABLE TIPO_FUNCION(
ID_TIPO_FUNCION SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
NOMBRE_TIPO CHAR(25) NOT NULL UNIQUE,
CONSTRAINT PK_TF PRIMARY KEY(ID_TIPO_FUNCION)
)

INSERT INTO TIPO_FUNCION (NOMBRE_TIPO) VALUES ('TRADICIONAL')
INSERT INTO TIPO_FUNCION (NOMBRE_TIPO) VALUES ('3D')
INSERT INTO TIPO_FUNCION (NOMBRE_TIPO) VALUES ('4D')
INSERT INTO TIPO_FUNCION (NOMBRE_TIPO) VALUES ('IMAX')

CREATE TABLE TIPO_SALA(
ID_TIPO_SALA SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
NOMBRE_TIPO CHAR(25) NOT NULL UNIQUE,
CONSTRAINT PK_TS PRIMARY KEY(ID_TIPO_SALA)
)

INSERT INTO TIPO_SALA (NOMBRE_TIPO) VALUES ('ESTANDAR')
INSERT INTO TIPO_SALA (NOMBRE_TIPO) VALUES ('VIP')
INSERT INTO TIPO_SALA (NOMBRE_TIPO) VALUES ('PREMIUM')
INSERT INTO TIPO_SALA (NOMBRE_TIPO) VALUES ('IMAX')
INSERT INTO TIPO_SALA (NOMBRE_TIPO) VALUES ('4DX')
INSERT INTO TIPO_SALA (NOMBRE_TIPO) VALUES ('MACRO')

--DROP TABLE TIPO_CINE 

CREATE TABLE TIPO_CINE(
ID_TIPO_CINE SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
TIPO_CINE CHAR(15) NOT NULL UNIQUE,
CONSTRAINT PK_TC PRIMARY KEY (ID_TIPO_CINE)
)

INSERT INTO TIPO_CINE(TIPO_CINE)VALUES('TRADICIONAL')
INSERT INTO TIPO_CINE(TIPO_CINE)VALUES('PREMIUM')
INSERT INTO TIPO_CINE(TIPO_CINE)VALUES('PLATINO-VIP')


--CREATE TABLE CINE_MARCA(
--ID_CINE SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
--NOMBRE CHAR(20) NOT NULL UNIQUE,
--CONSTRAINT PK_CM PRIMARY KEY (ID_CINE)
--)

--INSERT INTO CINE_MARCA(NOMBRE)VALUES('CINEMEX')
--INSERT INTO CINE_MARCA(NOMBRE)VALUES('CINEPOLIS')

CREATE TABLE IDIOMA_PROYECCION (
ID_IDIOMA SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
IDIOMA CHAR(30) NOT NULL UNIQUE,
CONSTRAINT PK_ID PRIMARY KEY (ID_IDIOMA)
)

INSERT INTO IDIOMA_PROYECCION(IDIOMA)VALUES('ESPAÑOL')
INSERT INTO IDIOMA_PROYECCION(IDIOMA)VALUES('INGLES')
INSERT INTO IDIOMA_PROYECCION(IDIOMA)VALUES('INGLES-SUB')

--CREATE TABLE AREAS(
--ID_AREA SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
--NOMBRE_AREA CHAR(20) NOT NULL UNIQUE,
--CONSTRAINT PK_AR PRIMARY KEY (ID_AREA)
--)

--INSERT INTO AREAS(NOMBRE_AREA)VALUES('SALAS')
--INSERT INTO AREAS(NOMBRE_AREA)VALUES('DULCERIA')
--INSERT INTO AREAS(NOMBRE_AREA)VALUES('CAFETERIA')
--INSERT INTO AREAS(NOMBRE_AREA)VALUES('ALMACEN')
--INSERT INTO AREAS(NOMBRE_AREA)VALUES('PAQUETERIA')
--INSERT INTO AREAS(NOMBRE_AREA)VALUES('JUEGOS')

CREATE TABLE PUESTOS(
ID_PUESTO SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
PUESTO VARCHAR(30) NOT NULL UNIQUE,
CONSTRAINT PK_IDP PRIMARY KEY (ID_PUESTO)
)

INSERT INTO PUESTOS(PUESTO)VALUES('GERENTE GENERAL')
INSERT INTO PUESTOS(PUESTO)VALUES('SUBGERENTE GENERAL')
INSERT INTO PUESTOS(PUESTO)VALUES('GERENTE DULCERIA')
INSERT INTO PUESTOS(PUESTO)VALUES('GERENTE VENTAS')
INSERT INTO PUESTOS(PUESTO)VALUES('VENDEDOR')
INSERT INTO PUESTOS(PUESTO)VALUES('LIMPIEZA')
INSERT INTO PUESTOS(PUESTO)VALUES('AUXILIAR DE ALMACEN')

--SELECT * FROM PUESTOS

CREATE TABLE TIPOS_PAGO(
ID_TIPO_PAGO SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
TIPO_PAGO CHAR(25) NOT NULL UNIQUE,
CONSTRAINT PK_IDTP PRIMARY KEY(ID_TIPO_PAGO)
)

INSERT INTO TIPOS_PAGO(TIPO_PAGO)VALUES('EFECTIVO')
INSERT INTO TIPOS_PAGO(TIPO_PAGO)VALUES('TARJETA DEBITO')
INSERT INTO TIPOS_PAGO(TIPO_PAGO)VALUES('TARJETA CREDITO')

CREATE TABLE TIPO_CLIENTES(
ID_TIPO_CLIENTE SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
TIPO_CLIENTE VARCHAR(50) NOT NULL UNIQUE,
CONSTRAINT PK_TCL PRIMARY KEY(ID_TIPO_CLIENTE)
)

INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('ESTANDAR GENERAL')
INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('ESTANDAR NIÑO')
INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('ESTANDAR ADULTO')

INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('CINEFAN GENERAL')
INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('CINEFAN NIÑO')
INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('CINEFAN ADULTO')

INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('SUPER FANATICO GENERAL')
INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('SUPER FANATICO NIÑO')
INSERT INTO TIPO_CLIENTES(TIPO_CLIENTE)VALUES('SUPER FANATICO ADULTO')


CREATE TABLE PELICULAS(
ID_PELICULA SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
TITULO VARCHAR(50) NOT NULL,
GENERO CHAR(25) NOT NULL,
CLACIFICACION CHAR(10) NOT NULL,
PAIS_ORIGEN VARCHAR(25),
--ANIO_ORIGEN INT NOT NULL,
FECHA_ESTRENO DATE,
DIRECTOR VARCHAR(50) NOT NULL,
PROTAGONISTA VARCHAR(100) NOT NULL,
DURACION SMALLINT NOT NULL,
SIPNOSIS VARCHAR(2000),
CONSTRAINT PK_PELI PRIMARY KEY (ID_PELICULA),
CHECK (DURACION <=300)
)

--ALTER TABLE SUCURSALES DROP COLUMN NUMERO_EMPLEADOS

CREATE TABLE SUCURSALES(
ID_SUCURSAL INT IDENTITY(1,1) NOT FOR REPLICATION,
CIUDAD VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(100) NOT NULL UNIQUE,
TELEFONO VARCHAR(10) NOT NULL UNIQUE,
HORA_INICIO TIME NOT NULL,
HORA_FIN TIME NOT NULL,
--NUMERO_EMPLEADOS SMALLINT,
--FK_MARCA_CINE SMALLINT,
FK_TIPO_CINE SMALLINT,
CONSTRAINT PK_IDS PRIMARY KEY(ID_SUCURSAL),
--CONSTRAINT FK_MARCA_CINE FOREIGN KEY(FK_MARCA_CINE) REFERENCES CINE_MARCA(ID_CINE) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_TIPO_CINE FOREIGN KEY(FK_TIPO_CINE) REFERENCES TIPO_CINE(ID_TIPO_CINE) ON DELETE NO ACTION ON UPDATE CASCADE
)

CREATE TABLE EMPLEADOS(
ID_EMPLEADO SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
NOMBRE VARCHAR(100) NOT NULL,
EDAD SMALLINT NOT NULL,
FECHA_INGRESO DATE NOT NULL,
FK_SUCURSAL INT,
FK_PUESTO SMALLINT,
CONSTRAINT PK_IDE PRIMARY KEY(ID_EMPLEADO),
CONSTRAINT FK_SUCEMP FOREIGN KEY(FK_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL)ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_PUESTO FOREIGN KEY(FK_PUESTO) REFERENCES PUESTOS(ID_PUESTO)ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT CH_VALEDAD CHECK (EDAD>=18)
)

--INSERT INTO EMPLEADOS(NOMBRE,EDAD,FECHA_INGRESO,FK_SUCURSAL)VALUES('KEVIN',24,GETDATE(),1)
--INSERT INTO EMPLEADOS(NOMBRE,EDAD,FECHA_INGRESO,FK_SUCURSAL)VALUES('KARLA',25,GETDATE(),1)
--INSERT INTO EMPLEADOS(NOMBRE,EDAD,FECHA_INGRESO,FK_SUCURSAL)VALUES('ADAN',26,GETDATE(),2)
--INSERT INTO EMPLEADOS(NOMBRE,EDAD,FECHA_INGRESO,FK_SUCURSAL)VALUES('JESUS',27,GETDATE(),2)

CREATE TABLE SALAS(
ID_SALA SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
NUMERO_SALA SMALLINT NOT NULL,
ESTATUS BIT DEFAULT 1 NOT NULL,
NUMERO_ASIENTOS SMALLINT,
FK_TIPO_SALA SMALLINT,
FK_SUCURSAL INT,
CONSTRAINT PK_SA PRIMARY KEY(ID_SALA),
CONSTRAINT FK_TCS FOREIGN KEY(FK_TIPO_SALA) REFERENCES TIPO_SALA(ID_TIPO_SALA) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_SUC FOREIGN KEY(FK_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL) ON DELETE NO ACTION ON UPDATE CASCADE
)

--CREATE TABLE AREAS_PUESTOS_EMPLEADOS(
--FK_AREA SMALLINT NOT NULL,
--FK_PUESTO SMALLINT NOT NULL,
--FK_EMPLEADO SMALLINT NOT NULL,
--CONSTRAINT FK_AR FOREIGN KEY (FK_AREA) REFERENCES AREAS(ID_AREA) ON DELETE NO ACTION ON UPDATE CASCADE,
--CONSTRAINT FK_P FOREIGN KEY(FK_PUESTO) REFERENCES PUESTOS(ID_PUESTO) ON DELETE NO ACTION ON UPDATE CASCADE,
--CONSTRAINT FK_EMP FOREIGN KEY(FK_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO) ON DELETE CASCADE ON UPDATE CASCADE
--)

--ALTER TABLE FUNCIONES ADD ESTATUS BIT DEFAULT 1

CREATE TABLE FUNCIONES(
ID_FUNCION SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
HORARIO TIME NOT NULL,
FK_SALA SMALLINT,
FK_PELI SMALLINT,
FK_IDIOMA SMALLINT,
FK_TFUNCION SMALLINT,
CONSTRAINT PK_FUN PRIMARY KEY(ID_FUNCION),
CONSTRAINT FK_SA FOREIGN KEY(FK_SALA)REFERENCES SALAS(ID_SALA) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_TF1 FOREIGN KEY(FK_TFUNCION) REFERENCES TIPO_FUNCION(ID_TIPO_FUNCION) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_PEL FOREIGN KEY(FK_PELI) REFERENCES PELICULAS(ID_PELICULA) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_ID FOREIGN KEY(FK_IDIOMA) REFERENCES IDIOMA_PROYECCION(ID_IDIOMA) ON DELETE NO ACTION ON UPDATE CASCADE
)

CREATE TABLE VENTAS(
ID_VENTA BIGINT IDENTITY(1,1),
FECHA_VENTA DATETIME DEFAULT GETDATE(),
MONTO_TOTAL DECIMAL(9,2) DEFAULT 0.0, --ESTE CAMPO SE VA A ACUALIZAR CUANDO SE REGISTRE UN NUEVO BOLETO
FK_EMPLEADO SMALLINT,
FK_TIPO_PAGO SMALLINT,
CONSTRAINT PK_VENTA PRIMARY KEY(ID_VENTA),
CONSTRAINT FK_EMP1 FOREIGN KEY(FK_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_TP FOREIGN KEY(FK_TIPO_PAGO) REFERENCES TIPOS_PAGO(ID_TIPO_PAGO) ON DELETE NO ACTION ON UPDATE CASCADE
)


CREATE TABLE PRECIOS_BOLETOS(
ID_PRECIO BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
PRECIO_INIT DECIMAL(9,2),
PORCENT_DESC DECIMAL(9,2),
MONTO_DESC DECIMAL(9,2), -- DEFAULT (SELECT (PRECIO_GENERAL*PORCENT_DESC) ), --SE DEBE CALCULAR EN UN TIGGER
PRECIO_FINAL DECIMAL(9,2) , --DEFAULT (SELECT (PRECIO_GENERAL-MONTO_DESC) ) ---SE DEBE CALCULAR EN UN TIGGER
FK_TFUNCION SMALLINT,
FK_TCLIENTE SMALLINT,
--FK_MARCA_CINE SMALLINT,
CONSTRAINT PK_PB PRIMARY KEY(ID_PRECIO),
CONSTRAINT FK_TFUN FOREIGN KEY (FK_TFUNCION) REFERENCES TIPO_FUNCION(ID_TIPO_FUNCION)ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_TC2 FOREIGN KEY(FK_TCLIENTE) REFERENCES TIPO_CLIENTES(ID_TIPO_CLIENTE)ON DELETE NO ACTION ON UPDATE CASCADE,
--CONSTRAINT FK_MC1 FOREIGN KEY(FK_MARCA_CINE) REFERENCES CINE_MARCA(ID_CINE)ON DELETE NO ACTION ON UPDATE CASCADE
)


CREATE TABLE BOLETOS(  --CADA QUE SE INSERTE UN BOLETO SE DEBE ACTUALIZAR EL CAMPO DEL MONTO TOTAL DE LA VENTA
ID_BOLETO BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
FECHA_COMPRA DATETIME DEFAULT GETDATE(),
FK_FUNCION SMALLINT,
FK_PRECIO_BOLETO BIGINT,
FK_VENTA BIGINT,
CONSTRAINT PK_BOL PRIMARY KEY(ID_BOLETO),
CONSTRAINT FK_FUN1 FOREIGN KEY(FK_FUNCION) REFERENCES FUNCIONES(ID_FUNCION) ON DELETE NO ACTION,
CONSTRAINT FK_PB FOREIGN KEY(FK_PRECIO_BOLETO) REFERENCES PRECIOS_BOLETOS(ID_PRECIO)ON DELETE NO ACTION,
CONSTRAINT FK_V1 FOREIGN KEY(FK_VENTA) REFERENCES VENTAS(ID_VENTA)ON DELETE NO ACTION
)

--CREATE TABLE VENTAS_FUNCION_CLIENTES(
--FK_VENTA BIGINT,
--FK_TIPO_CLIENTE SMALLINT,
--FK_TIPO_FUNCION SMALLINT,
--CONSTRAINT FK_V2 FOREIGN KEY(FK_VENTA) REFERENCES VENTAS(ID_VENTA)ON DELETE NO ACTION ON UPDATE CASCADE,
--CONSTRAINT FK_TC3 FOREIGN KEY(FK_TIPO_CLIENTE) REFERENCES TIPO_CLIENTES(ID_TIPO_CLIENTE)ON DELETE NO ACTION ON UPDATE CASCADE,
--CONSTRAINT FK_TFUN2 FOREIGN KEY(FK_TIPO_FUNCION) REFERENCES TIPO_FUNCION(ID_TIPO_FUNCION) ON DELETE NO ACTION ON UPDATE CASCADE
--)